### ISSUE TITLE
duplicate lines being sent to loki

### ISSUE THREAD

**Issue by cristianmtr** [GreyZmeem/python-logging-loki#9]
Hello

I am seeing that the LokiHandler gets called several times (up to 4 times) while the local logger only gets called once. Any idea why this could happen? Both with Queue and without

**Comment by GreyZmeem** [comment]
Hello!

Can you show your logging configuration?
The only thing that comes to mind is that the handler is used in several loggers and event is propagated from lower to higher level loggers (ancestors). In this case, one log record can be emitted multiple times.

**Comment by cristianmtr** [comment]
Yeah, it was that. Thanks for the help
